### ISSUE TITLE
haiku-fs-extra not found

### ISSUE THREAD

**Issue by Alioune05** [HaikuTeam/animator#1047]
Hello,

during my attempt to install Haiku on Win 10, i had an npm install error telling me haiku-fs-extra is not an npm package.
Wich is true, i cant found it on npm's web site.
![image](https://user-images.githubusercontent.com/48109941/134807075-06596a3e-b287-4993-ac55-53111b3d7e26.png)
![image](https://user-images.githubusercontent.com/48109941/134807083-e5ab0bda-b7f2-4e5a-b1a9-96e8c8c4717f.png)
Here is the log :
[2021-09-26T12_03_13_930Z-debug.log](https://github.com/HaikuTeam/animator/files/7231349/2021-09-26T12_03_13_930Z-debug.log)

**Comment by gumptious** [comment]
At the moment the Windows environment is not guaranteed to be working (haven't been able to test on a Windows machine since going OSS.) 

That said, please follow the README instructions for your best shot at getting it working. Looks like you're using `npm` instead of `yarn`, for example. See https://github.com/HaikuTeam/animator/#2-install-project-dependencies
